param:
  # corpus
  corpus: erato
  label_type: kana
  ss_type: insert_right

  # features
  feature: fbank
  input_size: 123
  splice: 1
  num_stack: 2
  num_skip: 2

  # topology
  encoder_type: blstm
  encoder_num_units: 256
  encoder_num_proj: None
  encoder_num_layers: 4
  attention_type: dot_product
  attention_dim: 128
  decoder_type: lstm
  decoder_num_units: 256
  decoder_num_layers: 1
  embedding_dim: 64
  max_decode_length: 100
  lstm_impl: LSTMBlockCell
  use_peephole: True

  # optimization
  batch_size: 32
  optimizer: rmsprop
  learning_rate: 1e-3
  num_epoch: 100

  # regularization
  weight_init: 0.1
  clip_grad_norm: 5.0
  clip_activation_encoder: 50
  clip_activation_decoder: 50
  dropout_encoder: 0.5
  dropout_decoder: 0.1
  dropout_embedding: 0.1
  weight_decay: 0
  decay_start_epoch: 10
  decay_rate: 0.5
  decay_patient_epoch: 3
  sort_stop_epoch: 10
  sharpening_factor: 1.0
  logits_temperature: 1.0
  sigmoid_smoothing: False
  not_improved_patient_epoch: 10

  eval_start_epoch: 5
  print_step: 100
  beam_width: 1
