param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  corpus: timit
  label_type: phone61
  num_classes: 61

  # features
  feature: fbank
  save_format: numpy
  input_channel: 41
  use_delta: True
  use_double_delta: True
  splice: 1
  num_stack: 1
  num_skip: 1
  dynamic_batching: False

  # topology
  model_type: ctc
  encoder_type: lstm
  conv_channels: []
  conv_kernel_sizes: []
  conv_strides: []
  poolings: []
  activation: relu
  batch_norm: False
  encoder_bidirectional: True
  encoder_residual: False
  encoder_dense_residual: False
  encoder_num_units: 256
  encoder_num_proj: 0
  encoder_num_layers: 5
  subsample_list:
    - False
    - False
    - False
    - False
    - False
  subsample_type: drop
  fc_list: []

  # optimization
  batch_size: 64
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 100
  convert_to_sgd_epoch: 20

  # initialization
  parameter_init_distribution: uniform
  parameter_init: 0.1
  recurrent_weight_orthogonal: True
  init_forget_gate_bias_with_one: True

  # regularization
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout: 0.5
  weight_decay: 1e-6
  logits_temperature: 1
  label_smoothing_prob: 0
  weight_noise_std: 1e-9

  # annealing
  decay_start_epoch: 10
  decay_rate: 0.95
  decay_patient_epoch: 2
  sort_stop_epoch: 100
  not_improved_patient_epoch: 10
  eval_start_epoch: 10
  print_step: 10
