param:
  model: multitask_blstm_ctc
  corpus: csj
  label_type_main: kanji
  label_type_sub: phone
  train_data_size: default
  feature: fbank
  input_size: 120
  num_stack: 3
  num_skip: 3
  num_unit: 320
  num_proj: 0
  num_layer_main: 5
  bottleneck_dim: 0
  num_layer_second: 3
  main_task_weight: 0.8
  batch_size: 32
  optimizer: adam
  learning_rate: 1e-3
  decay_steps: 12000
  decay_rate: 1
  num_epoch: 25
  weight_init: 0.1
  clip_grad: 5.0
  clip_activation: 50
  dropout_input: 1.0
  dropout_hidden: 0.8
  dropput_output: 1.0
  weight_decay: 0
