parent: ../config/attention/att_baseline.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # topology
  encoder_dense_residual: True

  # optimization
  batch_size: 64
  convert_to_sgd_epoch: 100

  # annealing
  print_step: 10
