param:
  # corpus
  corpus: librispeech
  label_type: word_freq10
  train_data_size: train460h

  # features
  feature: fbank
  input_size: 120
  splice: 1
  num_stack: 3
  num_skip: 3

  # topology
  encoder_type: blstm
  lstm_impl: LSTMBlockCell
  use_peephole: True
  num_units: 320
  num_proj: 0
  num_layers: 5
  bottleneck_dim: 0

  # optimization
  batch_size: 32
  optimizer: rmsprop
  learning_rate: 1e-3
  num_epoch: 20

  # regularization
  weight_init: 0.1
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout: 0.2
  weight_decay: 0
  decay_start_epoch: 5
  decay_rate: 0.5
  decay_patient_epoch: 3
  sort_stop_epoch: 3

  eval_start_epoch: 3
  print_step: 100
  beam_width: 20
