param:
  # corpus
  corpus: svc
  label_type: phone3

  # features
  feature: fbank
  input_size: 123
  splice: 1
  num_stack: 1
  num_skip: 1

  # topology
  encoder_type: blstm
  lstm_impl: LSTMBlockCell
  use_peephole: True
  num_units: 256
  num_proj: 0
  num_layers: 5
  bottleneck_dim: 0

  # optimization
  batch_size: 64
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 100

  # regularization
  weight_init: 0.1
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout: 0.5
  weight_decay: 0
  decay_start_epoch: 30
  decay_rate: 0.5
  decay_patient_epoch: 5
  sort_stop_epoch: 0  # not used

  eval_start_epoch: 30
  print_step: 10
  beam_width: 20
